# -*- coding: utf-8 -*-
"""calculadora_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19PykLhsbYsh0xPgDNfFYrndyA1XPpRPI
"""

def soma(x,y): return x+y
def subtracao(x,y): return x-y
def multiplicacao(x,y): return x*y
def divisao(x,y): return x/y

print(50*"*")
print("Calculadora Python")
print(50*'*')
print()
print("Selecione a operação desejada:\n")
print("1 - Soma\n2 - Subtração\n3 - Multiplicação\n4 - Divisão\n")
opcao = int(input("Digite sua opção (1,2,3,4):\n "))
num = int(input("Digite o primeiro número:"))
print()
num2 = int(input("Digite o segundo número:"))

if opcao == 1:
  print()
  print(num, "+",num2,"=",soma(num,num2))
  print()
elif opcao == 2:
  print()
  print(num, "-",num2,"=",subtracao(num,num2))
  print()
elif opcao == 3:
  print()
  print(num, "*",num2,"=",multiplicacao(num,num2))
  print()
elif opcao == 4:
  print()
  print(num, "/",num2,"=",divisao(num,num2))
  print()
else:
  print("Opção inválida")